before_script:
    - echo "$PRODUCTION_S3CMD_CONFIGURATION" > $HOME/.s3cfg

cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
        - node_modules

stages:
    - build
    - deploy

deploy:production:
    image: registry.furqansoftware.net/islamipathshala/pwapp/foundry:2020.02.0
    stage: deploy
    environment:
        name: production
        url: https://islamipathshala.com/
    only:
        - master
    script:
        - echo "$PRODUCTION_HUGO_CONFIGURATION" > config.toml
        - npm install
        - npm run build
        - find public -size 0 -type f -delete
        - rm public/sitemap.xml
        - s3cmd sync --delete-removed --delete-after --acl-public public/ s3://$PRODUCTION_S3_BUCKET_NAME
    when: manual
