cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
        - node_modules

stages:
    - build
    - production

production:
    image: registry.furqansoftware.net/islamipathshala/pwapp/foundry:2021.01.0
    stage: production
    environment:
        name: production
        url: https://islamipathshala.com/
    only:
        - tags
    script:
        - npm install --also=dev
        - npm run build
        - sed -i s/"s3:\\/\\/$PRODUCTION_S3_BUCKET_NAME"/"&?region=$PRODUCTION_AWS_REGION\\&endpoint=$PRODUCTION_AWS_ENDPOINT\\&s3ForcePathStyle=true"/ config.toml
        - hugo
        - AWS_ACCESS_KEY_ID=$PRODUCTION_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$PRODUCTION_AWS_SECRET_ACCESS_KEY hugo deploy
        - echo "$PRODUCTION_S3CMD_CONFIGURATION" > $HOME/.s3cfg
        - s3cmd setacl -rP s3://$PRODUCTION_S3_BUCKET_NAME/
    artifacts:
        expire_in: 1 day
        paths:
            - public/
